title: severalfly 个人博客
description: severalfly 个人博客，一起分享知识
show_downloads: true
google_analytics: UA-93353924-1
theme: 

collections:
  my_posts:  # 自定义集合名称
    output: true  # 是否生成独立页面
    permalink: /my_posts/:path/  # 自定义URL结构
